// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package db

import (
	"context"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents(email,clerk_id,name,invited, role)
VALUES ($1,$2,$3,$4,$5)
RETURNING id, email, name, website_id, role, clerk_id, invited, created_at, updated_at
`

type CreateAgentParams struct {
	Email   string `json:"email"`
	ClerkID string `json:"clerk_id"`
	Name    string `json:"name"`
	Invited *bool  `json:"invited"`
	Role    string `json:"role"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.Email,
		arg.ClerkID,
		arg.Name,
		arg.Invited,
		arg.Role,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.WebsiteID,
		&i.Role,
		&i.ClerkID,
		&i.Invited,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findByEmail = `-- name: FindByEmail :one
SELECT id, email, name, website_id, role, clerk_id, invited, created_at, updated_at
FROM agents
WHERE email = $1
LIMIT 1
`

func (q *Queries) FindByEmail(ctx context.Context, email string) (Agent, error) {
	row := q.db.QueryRow(ctx, findByEmail, email)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.WebsiteID,
		&i.Role,
		&i.ClerkID,
		&i.Invited,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
