// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversation.sql

package db

import (
	"context"
)

const assignAgent = `-- name: AssignAgent :one
UPDATE conversations
SET agent_id = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, visitor_id, agent_id, status, created_at, updated_at
`

type AssignAgentParams struct {
	ID      int32  `json:"id"`
	AgentID *int64 `json:"agent_id"`
}

func (q *Queries) AssignAgent(ctx context.Context, arg AssignAgentParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, assignAgent, arg.ID, arg.AgentID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.VisitorID,
		&i.AgentID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const closeConversation = `-- name: CloseConversation :exec
UPDATE conversations
SET status = 'closed',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) CloseConversation(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, closeConversation, id)
	return err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (visitor_id)
VALUES ($1)
RETURNING id, visitor_id, agent_id, status, created_at, updated_at
`

func (q *Queries) CreateConversation(ctx context.Context, visitorID *string) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, visitorID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.VisitorID,
		&i.AgentID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, visitor_id, agent_id, status, created_at, updated_at
FROM conversations
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetConversation(ctx context.Context, id int32) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.VisitorID,
		&i.AgentID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversationsByStatus = `-- name: ListConversationsByStatus :many
SELECT id, visitor_id, agent_id, status, created_at, updated_at
FROM conversations
WHERE status = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListConversationsByStatus(ctx context.Context, status string) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversationsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.VisitorID,
			&i.AgentID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationsByVisitor = `-- name: ListConversationsByVisitor :many
SELECT id, visitor_id, agent_id, status, created_at, updated_at
FROM conversations
WHERE visitor_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListConversationsByVisitor(ctx context.Context, visitorID *string) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversationsByVisitor, visitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.VisitorID,
			&i.AgentID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversationStatus = `-- name: UpdateConversationStatus :exec
UPDATE conversations
SET status = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateConversationStatusParams struct {
	ID     int32  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateConversationStatus(ctx context.Context, arg UpdateConversationStatusParams) error {
	_, err := q.db.Exec(ctx, updateConversationStatus, arg.ID, arg.Status)
	return err
}
