// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversation.sql

package db

import (
	"context"
)

const assignAgent = `-- name: AssignAgent :one
UPDATE conversations
SET agent_id = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, visitor_id, agent_id, status, website_id, created_at, updated_at
`

type AssignAgentParams struct {
	ID      int32  `json:"id"`
	AgentID *int64 `json:"agent_id"`
}

func (q *Queries) AssignAgent(ctx context.Context, arg AssignAgentParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, assignAgent, arg.ID, arg.AgentID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.VisitorID,
		&i.AgentID,
		&i.Status,
		&i.WebsiteID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const closeConversation = `-- name: CloseConversation :exec
UPDATE conversations
SET status = 'closed',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) CloseConversation(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, closeConversation, id)
	return err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (visitor_id)
VALUES ($1)
RETURNING id, visitor_id, agent_id, status, website_id, created_at, updated_at
`

func (q *Queries) CreateConversation(ctx context.Context, visitorID *string) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, visitorID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.VisitorID,
		&i.AgentID,
		&i.Status,
		&i.WebsiteID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findOpenConversation = `-- name: FindOpenConversation :one
SELECT id, visitor_id, agent_id, status, website_id, created_at, updated_at
FROM conversations
WHERE website_id = $1
  AND visitor_id = $2
  AND status = 'open'
ORDER BY created_at DESC
LIMIT 1
`

type FindOpenConversationParams struct {
	WebsiteID *int32  `json:"website_id"`
	VisitorID *string `json:"visitor_id"`
}

func (q *Queries) FindOpenConversation(ctx context.Context, arg FindOpenConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, findOpenConversation, arg.WebsiteID, arg.VisitorID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.VisitorID,
		&i.AgentID,
		&i.Status,
		&i.WebsiteID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findOpenConversationById = `-- name: FindOpenConversationById :one
SELECT 1
FROM conversations
WHERE id = $1
  AND website_id=$2
  AND status = 'open'
LIMIT 1
`

type FindOpenConversationByIdParams struct {
	ID        int32  `json:"id"`
	WebsiteID *int32 `json:"website_id"`
}

func (q *Queries) FindOpenConversationById(ctx context.Context, arg FindOpenConversationByIdParams) (int32, error) {
	row := q.db.QueryRow(ctx, findOpenConversationById, arg.ID, arg.WebsiteID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const findOrCreateOpenConversation = `-- name: FindOrCreateOpenConversation :one
INSERT INTO conversations (website_id, visitor_id, status)
VALUES ($1, $2, 'open')
ON CONFLICT (website_id, visitor_id)
WHERE status = 'open'
DO UPDATE SET
  website_id = conversations.website_id
RETURNING id
`

type FindOrCreateOpenConversationParams struct {
	WebsiteID *int32  `json:"website_id"`
	VisitorID *string `json:"visitor_id"`
}

func (q *Queries) FindOrCreateOpenConversation(ctx context.Context, arg FindOrCreateOpenConversationParams) (int32, error) {
	row := q.db.QueryRow(ctx, findOrCreateOpenConversation, arg.WebsiteID, arg.VisitorID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, visitor_id, agent_id, status, website_id, created_at, updated_at
FROM conversations
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetConversation(ctx context.Context, id int32) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.VisitorID,
		&i.AgentID,
		&i.Status,
		&i.WebsiteID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversationsByStatus = `-- name: ListConversationsByStatus :many
SELECT id, visitor_id, agent_id, status, website_id, created_at, updated_at
FROM conversations
WHERE status = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListConversationsByStatus(ctx context.Context, status string) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversationsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.VisitorID,
			&i.AgentID,
			&i.Status,
			&i.WebsiteID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationsByVisitor = `-- name: ListConversationsByVisitor :many
SELECT id, visitor_id, agent_id, status, website_id, created_at, updated_at
FROM conversations
WHERE visitor_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListConversationsByVisitor(ctx context.Context, visitorID *string) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversationsByVisitor, visitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.VisitorID,
			&i.AgentID,
			&i.Status,
			&i.WebsiteID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversationStatus = `-- name: UpdateConversationStatus :exec
UPDATE conversations
SET status = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateConversationStatusParams struct {
	ID     int32  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateConversationStatus(ctx context.Context, arg UpdateConversationStatusParams) error {
	_, err := q.db.Exec(ctx, updateConversationStatus, arg.ID, arg.Status)
	return err
}
