// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"
)

const countMessages = `-- name: CountMessages :one
SELECT COUNT(*)
FROM messages
WHERE conversation_id = $1
`

func (q *Queries) CountMessages(ctx context.Context, conversationID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countMessages, conversationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (conversation_id, sender_type, sender_id, content)
VALUES ($1, $2, $3, $4)
RETURNING id, conversation_id, sender_type, sender_id, content, created_at
`

type CreateMessageParams struct {
	ConversationID int32   `json:"conversation_id"`
	SenderType     string  `json:"sender_type"`
	SenderID       *string `json:"sender_id"`
	Content        string  `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ConversationID,
		arg.SenderType,
		arg.SenderID,
		arg.Content,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderType,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages
WHERE id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteMessage, id)
	return err
}

const listMessagesByConversation = `-- name: ListMessagesByConversation :many
SELECT id, conversation_id, sender_type, sender_id, content, created_at
FROM messages
WHERE conversation_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListMessagesByConversation(ctx context.Context, conversationID int32) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderType,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
