// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID        int32            `json:"id"`
	Email     string           `json:"email"`
	Name      string           `json:"name"`
	WebsiteID *int32           `json:"website_id"`
	Role      string           `json:"role"`
	ClerkID   string           `json:"clerk_id"`
	Invited   *bool            `json:"invited"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type AgentInvite struct {
	ID        int32            `json:"id"`
	WebsiteID int32            `json:"website_id"`
	Email     string           `json:"email"`
	InvitedBy int32            `json:"invited_by"`
	Token     string           `json:"token"`
	Accepted  *bool            `json:"accepted"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Conversation struct {
	ID        int32            `json:"id"`
	VisitorID *string          `json:"visitor_id"`
	AgentID   *int64           `json:"agent_id"`
	Status    string           `json:"status"`
	WebsiteID *int32           `json:"website_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Message struct {
	ID             int32            `json:"id"`
	ConversationID int32            `json:"conversation_id"`
	SenderType     string           `json:"sender_type"`
	SenderID       *string          `json:"sender_id"`
	Content        string           `json:"content"`
	WebsiteID      *int32           `json:"website_id"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type Visitor struct {
	ID        string           `json:"id"`
	IpAddress *string          `json:"ip_address"`
	UserAgent *string          `json:"user_agent"`
	State     *string          `json:"state"`
	Country   *string          `json:"country"`
	WebsiteID *int32           `json:"website_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Website struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Host      *string          `json:"host"`
	ApiKey    string           `json:"api_key"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
