// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: visitors.sql

package db

import (
	"context"
)

const createVisitor = `-- name: CreateVisitor :one
INSERT INTO visitors (ip_address, state, country, website_id, user_agent)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, ip_address, user_agent, state, country, website_id, created_at
`

type CreateVisitorParams struct {
	IpAddress *string `json:"ip_address"`
	State     *string `json:"state"`
	Country   *string `json:"country"`
	WebsiteID *int32  `json:"website_id"`
	UserAgent *string `json:"user_agent"`
}

func (q *Queries) CreateVisitor(ctx context.Context, arg CreateVisitorParams) (Visitor, error) {
	row := q.db.QueryRow(ctx, createVisitor,
		arg.IpAddress,
		arg.State,
		arg.Country,
		arg.WebsiteID,
		arg.UserAgent,
	)
	var i Visitor
	err := row.Scan(
		&i.ID,
		&i.IpAddress,
		&i.UserAgent,
		&i.State,
		&i.Country,
		&i.WebsiteID,
		&i.CreatedAt,
	)
	return i, err
}

const getVisitor = `-- name: GetVisitor :one
SELECT id, ip_address, user_agent, state, country, website_id, created_at
FROM visitors
WHERE id = $1
`

func (q *Queries) GetVisitor(ctx context.Context, id string) (Visitor, error) {
	row := q.db.QueryRow(ctx, getVisitor, id)
	var i Visitor
	err := row.Scan(
		&i.ID,
		&i.IpAddress,
		&i.UserAgent,
		&i.State,
		&i.Country,
		&i.WebsiteID,
		&i.CreatedAt,
	)
	return i, err
}
