// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: websites.sql

package db

import (
	"context"
)

const createWebsite = `-- name: CreateWebsite :one

INSERT INTO websites(name, domain, public_key, secret_hash)
values($1,$2,$3,$4)
RETURNING id, name, domain, public_key, secret_hash, created_at, is_active, settings
`

type CreateWebsiteParams struct {
	Name       string `json:"name"`
	Domain     string `json:"domain"`
	PublicKey  string `json:"public_key"`
	SecretHash string `json:"secret_hash"`
}

func (q *Queries) CreateWebsite(ctx context.Context, arg CreateWebsiteParams) (Website, error) {
	row := q.db.QueryRow(ctx, createWebsite,
		arg.Name,
		arg.Domain,
		arg.PublicKey,
		arg.SecretHash,
	)
	var i Website
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.PublicKey,
		&i.SecretHash,
		&i.CreatedAt,
		&i.IsActive,
		&i.Settings,
	)
	return i, err
}
